config/routes.rb
ControleEscola::Application.routes.draw do
  resources :alunos

  resources :professores

  root :to => "home#index"
  devise_for :users

end

app/models/aluno.rb
class Aluno < ActiveRecord::Base
  attr_accessible :email, :nascimento, :nome
  attr_readonly :user
  has_one :user, :as => :usuario


  def initialize(attributes= nil )
    super(attributes)
    self.send("#{:user}=",User.cria_usuario_para(self))
  end


end

app/models/professor.rb
# -*- coding: UTF-8 -*

class Professor < ActiveRecord::Base
  attr_accessible :graduacao,:nascimento, :nome, :email
  attr_readonly   :user
  attr_accessor   :email
  has_one :user, :as => :usuario, :foreign_key => "id",:autosave => true
  #VALIDADTIONS
  validates_presence_of :nome, message: "Nome deve ser preenchido"
  validates_presence_of :graduacao, message: "Professor deve ter uma gradução"
  #validates_uniqueness_of :email, message: "O email dever ser único"
  #validate :email_is_valid




  def initialize(attributes= nil )
  #this looks like bad practice
  #Someone have idea to how make it more better...
    email = nil;
    if(attributes)
      email = attributes[:email];
      attributes.delete(:email)
    end
    super(attributes)
    self.email = email
    self.send("#{:user}=",User.cria_usuario_para(self))
  end

  def email
    if(read_attribute(:user))
        return self.user.email
     else
        return "testess@gmail.com"   
     end   
  end  



end

app/models/user.rb
# -*- coding: UTF-8 -*

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  #Uers can belongs everyone which acess system: Students e Teachers
  #Polyphormic association is necessary
  belongs_to :user,:polymorphic => true
  ROLES = %w[Aluno Administador Professor]



  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me,:role, :update_at
  # attr_accessible :title, :body

  #def initialize(attributes= nil )
   # if (attributes)
    #  attributes.store(:update_at,Time.now)
    #end
    #super(attributes)
  #end


  def e_professor?
    return role.eql? "Professor"
  end

  def e_aluno?
    return role.eql? "Aluno"
  end

  #Before this method was called criaUsuarioPara
  # It's me thinking as java' programmer
  #def self.criaUsuarioPara(funcao)
  def self.cria_usuario_para(funcao)
    #Cuidando com is or Kind porque retornam true para superclasse
    #http://stackoverflow.com/questions/3893278/ruby-kind-of-vs-instance-of-vs-is-a
    if funcao.instance_of? Professor or funcao.instance_of? Aluno
      return cria_usuario_do(funcao)
    else
      raise TypeError, 'Só pode ser criado usuário para Professores ou alunos'
    end
  end

  #Credits to http://stackoverflow.com/questions/5966910/generate-unique-random-string-with-letters-and-numbers-in-lower-case
  #It's so easy add arrays.Don't look like real
  def self.cria_password(tamanho)
    array = (?0..?9).to_a + (?a..?z).to_a
    password = tamanho.times.inject("") {|s, i| s << array[rand(array.size)]}
    return password
  end

  private
  def self.cria_usuario_do(funcao)
    role = cria_role_para(funcao)
    password = cria_password(8)
    return User.new :email => funcao.email,
                    :role => cria_role_para(funcao),
                    :password => password,
                    :password_confirmation => password
  end



  private
  def self.cria_role_para(funcao)
    if funcao.instance_of? Professor
        return "Professor"
    else
       return  "Aluno"
    end
  end

end

app/controllers/alunos_controller.rb
class AlunosController < ApplicationController
  # GET /alunos
  # GET /alunos.json
  def index
    @alunos = Aluno.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @alunos }
    end
  end

  # GET /alunos/1
  # GET /alunos/1.json
  def show
    @aluno = Aluno.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @aluno }
    end
  end

  # GET /alunos/new
  # GET /alunos/new.json
  def new
    @aluno = Aluno.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @aluno }
    end
  end

  # GET /alunos/1/edit
  def edit
    @aluno = Aluno.find(params[:id])
  end

  # POST /alunos
  # POST /alunos.json
  def create
    @aluno = Aluno.new(params[:aluno])

    respond_to do |format|
      if @aluno.save
        format.html { redirect_to @aluno, notice: 'Aluno was successfully created.' }
        format.json { render json: @aluno, status: :created, location: @aluno }
      else
        format.html { render action: "new" }
        format.json { render json: @aluno.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /alunos/1
  # PUT /alunos/1.json
  def update
    @aluno = Aluno.find(params[:id])

    respond_to do |format|
      if @aluno.update_attributes(params[:aluno])
        format.html { redirect_to @aluno, notice: 'Aluno was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @aluno.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alunos/1
  # DELETE /alunos/1.json
  def destroy
    @aluno = Aluno.find(params[:id])
    @aluno.destroy

    respond_to do |format|
      format.html { redirect_to alunos_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/professores_controller.rb
class ProfessoresController < ApplicationController
  # GET /professores
  # GET /professores.json
  def index
    @professores = Professor.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @professores }
    end
  end

  # GET /professores/1
  # GET /professores/1.json
  def show
    @professor = Professor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @professor }
    end
  end

  # GET /professores/new
  # GET /professores/new.json
  def new
    @professor = Professor.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @professor }
    end
  end

  # GET /professores/1/edit
  def edit
    @professor = Professor.find(params[:id])
  end

  # POST /professores
  # POST /professores.json
  def create
    @professor = Professor.new(params[:professor])

    respond_to do |format|
      if @professor.save
        format.html { redirect_to @professor, notice: 'Professor was successfully created.' }
        format.json { render json: @professor, status: :created, location: @professor }
      else
        format.html { render action: "new" }
        format.json { render json: @professor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /professores/1
  # PUT /professores/1.json
  def update
    @professor = Professor.find(params[:id])

    respond_to do |format|
      if @professor.update_attributes(params[:professor])
        format.html { redirect_to @professor, notice: 'Professor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @professor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /professores/1
  # DELETE /professores/1.json
  def destroy
    @professor = Professor.find(params[:id])
    @professor.destroy

    respond_to do |format|
      format.html { redirect_to professores_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/alunos_helper.rb
module AlunosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def twitterized_type(type)
    case type
      when :alert
        "alert-block"
      when :error
        "alert-error"
      when :notice
        "alert-info"
      when :success
        "alert-success"
      else
        type.to_s
    end
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/professores_helper.rb
module ProfessoresHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/views/alunos/_form.html.erb
<%= form_for @aluno, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :nome, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :nome, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :nascimento, :class => 'control-label' %>
    <div class="controls">
      <%= f.datetime_select :nascimento, :class => 'datetime_select' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :email, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                alunos_path, :class => 'btn' %>
  </div>
<% end %>

app/views/alunos/edit.html.erb
<%- model_class = Aluno -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/alunos/index.html.erb
<%- model_class = Aluno -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:código) %></th>
      <th><%= model_class.human_attribute_name(:nome) %></th>
      <th><%= model_class.human_attribute_name(:nascimento) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @alunos.each do |aluno| %>
      <tr>
        <td><%= link_to aluno.id, aluno_path(aluno) %></td>
        <td><%= aluno.nome %></td>
        <td><%=  aluno.nascimento %></td>
        <td><%= aluno.email %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_aluno_path(aluno), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      aluno_path(aluno),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_aluno_path,
            :class => 'btn btn-primary' %>

app/views/alunos/new.html.erb
<%- model_class = Aluno -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/alunos/show.html.erb
<%- model_class = Aluno -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:nome) %>:</strong></dt>
  <dd><%= @aluno.nome %></dd>
  <dt><strong><%= model_class.human_attribute_name(:nascimento) %>:</strong></dt>
  <dd><%= @aluno.nascimento %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @aluno.email %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              alunos_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_aluno_path(@aluno), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              aluno_path(@aluno),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>

  <title>Controle de Escola</title>
  <%= stylesheet_link_tag "application", :media => "all"  %>
  <%= favicon_link_tag '/favicon.ico' %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body>
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container-fluid">

      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="#">Controle de Escola</a>
      <% if user_signed_in? %>
      <div class="nav-collapse">
        <ul class="nav">
          <li class="active"><a href="#">Home</a></li>
          <li><a href="#about">About</a></li>

        </ul>
            <p class="navbar-text pull-right">Logged in as <%= current_user.email %>
                <%= link_to "logout", destroy_user_session_path, :method => :delete %>
            </p>
         <% end %>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>
<div class="container-fluid">
  <div class="row-fluid row">
    <div class="span3">
      <div class="well sidebar-nav-fixed">
       <div class="accordion" id="accordion2">
        <div class="accordion-group">
          <div class="accordion-heading">
            <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
              Controle de Usuários
            </a>
          </div>
          <div id="collapseOne" class="accordion-body collapse in">
            <div class="accordion-inner">
              <%= link_to :Professores, professores_path %>
            </div>
            <div class="accordion-inner">
              <%= link_to :Alunos,  alunos_path %>
            </div>

          </div>
        </div>
        <div class="accordion-group">
          <div class="accordion-heading">
            <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo">
              Collapsible Group Item #2
            </a>
          </div>
          <div id="collapseTwo" class="accordion-body collapse">
            <div class="accordion-inner">
              Anim pariatur cliche...
            </div>
          </div>
        </div>
      </div>
      </div><!--/.well -->
    </div><!--/span-->







    <div class="span9 span-fixed-sidebar">
      <div class="hero-unit">
        <div class="page-header">
          <%= yield :h1 %>
        </div>
        <%= render :partial => '/shared/flash_messages' %>
        <%= yield %>
      </div>


  <hr>



</div><!--/.fluid-container-->


</body>
</html>

app/views/professores/_form.html.erb
<%= simple_form_for(@professor, :html => { :class => 'form-vertical' })  do |f| %>
    <% content_for :h1 do %>
        Cadastro de Professor
    <% end %>

    <% if notification = f.error_notification %>
        <div class="alert alert-error fade in">
          <a class="close" data-dismiss="alert" href="#">&times;</a>
          <%= notification %>
        </div>
    <% end %>
    <% if @professor.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@professor.errors.count, "error") %> prohibited this cliente from being saved:</h2>

          <ul>
            <% @professor.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>








    <%= f.input :nome, :input_html => { :class => 'text_field span12' }%>
    <%= f.input :email %>
    <%= f.input :nascimento, :as => :string,  :input_html => { data: {behaviour: "datepicker"}} %>
    <%= f.input :graduacao, :as => :text, :input_html => { :cols => 80, :rows => 10,:class => 'text_area span12' } %>

    <div class="form-actions">
        <%= f.button :submit, :class => 'btn btn-primary' %>
        <%= f.button :button, 'Cancel', :type => 'reset', :class => 'btn btn-danger' %>
    </div>
<% end %>

app/views/professores/edit.html.erb
<%- model_class = Professor -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/professores/index.html.erb
<%- model_class = Professor -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:código) %></th>
      <th><%= model_class.human_attribute_name(:nome) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @professores.each do |professor| %>
      <tr>
        <td><%= link_to professor.id, professor_path(professor) %></td>
        <td><%= professor.nome %></td>
        <td><%= professor.email %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_professor_path(professor), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      professor_path(professor),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_professor_path,
            :class => 'btn btn-primary' %>

app/views/professores/new.html.erb
<%= render :partial => 'form' %>

app/views/professores/show.html.erb
<%- model_class = Professor -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:nome) %>:</strong></dt>
  <dd><%= @professor.nome %></dd>
  <dt><strong><%= model_class.human_attribute_name(:nascimento) %>:</strong></dt>
  <dd><%= @professor.nascimento %></dd>
  <dt><strong><%= model_class.human_attribute_name(:graduacao) %>:</strong></dt>
  <dd><%= @professor.graduacao %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @professor.email %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              professores_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_professor_path(@professor), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              professor_path(@professor),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/shared/_flash_messages.html.erb
<% [:notice, :error, :alert].each do |level| %>
    <% unless flash[level].blank? %>
        <div data-alert="alert" class="alert-message <%= twitterized_type(level) %> fade in">
          <a class="close" href="#">×</a>
          <%= content_tag :p, flash[level] %>
        </div>
    <% end %>
<% end %>